name: CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm, pnpm cache and turbo cache
        uses: ./.github/actions/setup-pnpm-turbo

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm, pnpm cache and turbo cache
        uses: ./.github/actions/setup-pnpm-turbo

      - name: Install dependencies
        run: pnpm install

      - name: Run Turbo build
        run: pnpm build
